server.port=8080
spring.application.name=genzen

# DATABASE DEV CONFIG WITH H2
# spring.datasource.url=jdbc:h2:file:./data/genzen;MODE=PostgreSQL
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=sa
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# DATABASE PROD CONFIG WITH POSTGRES
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.open-in-view=false

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:import.sql

app.cors.allowed-origin-patterns=http://localhost:*,http://127.0.0.1:*,http://192.168.*:*,http://10.*:*
